# config/routes.yaml

homepage:
    path: /
    controller: App\Controller\CalculateVatController::calculateVat
    methods: [GET, POST]

calculate_vat:
    path: /calculate-vat
    controller: App\Controller\CalculateVatController::calculateVat
    methods: [GET,POST]

# config/routes.yaml

clear_history:
    path: /clear-history
    controller: App\Controller\CalculateVatController::clearHistory
    methods: [POST]
